version: "3.8"
services:
  api:
    container_name: exampulumi_api
    tty: true
    stdin_open: true
    build:
      context: ./backend
      dockerfile: local.Dockerfile
    command: uvicorn src.main:app --reload --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: exampulumi_db
    image: postgres:13
    volumes:
      - ./db_data/pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  test_db:
    container_name: test_db
    image: postgres:13
    volumes:
      - ./test_db_data/pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "2346:5432"

  ui:
    container_name: ui
    build:
      context: ./ui
    stdin_open: true
    tty: true
    volumes:
      - ./ui:/ui
    ports:
    - "80:3000"
