"""Make item title unique

Revision ID: 4f1ca82eed28
Revises: 7166024f08bc
Create Date: 2023-10-28 12:04:34.155374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1ca82eed28'
down_revision: Union[str, None] = '7166024f08bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'title',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.create_unique_constraint(None, 'item', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='unique')
    op.alter_column('item', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
